### ISSUE TITLE
Unable to get multiple instances of jira module to show up

### ISSUE THREAD

**Issue by arashous** [wtfutil/wtf#1027]
## What's broken?

I am trying to implement multiple instances of the Jira module in my dashboard. Each one showing the results of a different jql query. 

I followed the documentation here for adding multiple instances, https://wtfutil.com/configuration/advanced/#multiple-instances-of-the-same-widget, by adding the **type: jira** to the config blocks. But it seems that only the last one listed in my config file seems to load. The other(s) are blank with no errors.

Here is what my config looks like

```
    # First Jira module instance
    jira:
      apiKey: "MYKEY"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "MYJIRAURL"
      email: "MYEMAIL"
      enabled: true
      jql: 'status in ("In Progress", Selected) AND resolution = Unresolved AND assignee in (currentUser())'
      position:
        top: 2
        left: 1
        height: 1
        width: 3
      project: ""
      refreshInterval: 100
      username: "MYUSERNAME"
      verifyServerCertificate: true 
      title: "Jira Unique Title 1" 
      type: jira 
    # Second Jira module instance
    jira:
      apiKey: "MYKEY"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "MYJIRAURL"
      email: "MYEMAIL"
      enabled: true
      jql: 'resolution = Unresolved AND assignee in (currentUser())'
      position:
        top: 3
        left: 1
        height: 1
        width: 3
      project: ""
      refreshInterval: 100
      username: "MYUSERNAME"
      verifyServerCertificate: true 
      title: "Jira Unique Title 2" 
      type: jira 
```

Some details about my setup in case it helps
- Using onprem (self hosted) jira, with username/password for authentication
- Using same credentials for both Jira module instances
