### ISSUE TITLE
Multi-config support

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#1031]
## What should it do?

Allow WTF to support multiple configuration files at the same time. Pseudo-config:

```yaml
wtf:
  configs:
    - personal_config.yml
    - work_config.yml
    - monitoring.yml
```

and provide a global key command to switch between them.
