### ISSUE TITLE
cryptolive not updates prices

### ISSUE THREAD

**Issue by zye1996** [wtfutil/wtf#1041]
Hi, it seems that cryptolive module is not updating the prices while toplists works fine. 

according to [here](https://github.com/wtfutil/wtf/blob/master/modules/cryptoexchanges/cryptolive/price/widget.go), I tried to make request to ```https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=```, there is nothing returned from server, while ```https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD``` returned a correct result.

The attached image shows what I get from the current configuration in the document:
![Screen Shot 2021-01-02 at 3 44 11 PM](https://user-images.githubusercontent.com/28901953/103466265-6806f000-4d11-11eb-9dbb-eb8084787777.png)

And here is my config:

```
cryptolive:
  enabled: true
  position:
    top: 5
    left: 2
    height: 1
    width: 2
  updateInterval: 15
  currencies:
    BTC:
      displayName: Bitcoin
      to:
        - USD
        - EUR
        - ETH
        - LTC
        - DOGE
    LTC:
      displayName: Ethereum
      to:
        - USD
        - EUR
        - BTC
  top:
    BTC:
      displayName: Bitcoin
      limit: 5
      to:
        - USD
  colors:
    from:
      name: coral
      displayName: grey
    to:
      name: white
      price: green
    top:
      from:
        name: grey
        displayName: coral
      to:
        name: red
        field: white
        value: green
```
