### ISSUE TITLE
Add Phabricator Integration

### ISSUE THREAD

**Issue by Quazie** [wtfutil/wtf#106]
Phabricator integration would be pretty awesome

**Comment by senorprogrammer** [comment]
Indeed it would. I don't use Phabricator so if someone who does wants to take a shot at it, by all means.

**Comment by alanc10n** [comment]
@Quazie : Do you have a clear idea of what data fields you'd want to see for this? Number of tickets assigned to you, number of pending code reviews, other things?

**Comment by Qoyyuum** [comment]
@alanc10n Phabricator has a lot of things installed. Perhaps on a module per module basis to divide this feature up?

**Comment by Quazie** [comment]
I feel like a way to get maniphest or diffusion query summary would be a
good start.

**Comment by hverlin** [comment]
As a workaround, you can create a script `ready_to_review` using `arc` and `jq`.
```
cd <directory> && echo '{"reviewers": ["PHID-USER-<user-id[1]>"],"status":"status-open"}' | arc call-conduit differential.query | jq -r '.response[] | .title, .uri,""'
```
(don't forget to mark it executable/add it to `$PATH`)

You can then use the cmd runner widget:
```yaml
    phab_reviews:
      type: cmdrunner
      args: ["ready_to_review"]
      cmd: 'bash'
      enabled: true
      position:
        top: 0
        left: 0
        height: 3
        width: 3
      refreshInterval: 30
```
-------
[1] Use https://<instance>/conduit/method/phid.lookup/ with your username (so @<user>) to get your PHID
