### ISSUE TITLE
Jira does not load up,  error "http: read on closed response body"

### ISSUE THREAD

**Issue by Orthdron** [wtfutil/wtf#1070]
```
Version: 0.36.0 (2021-03-23T12:48:25+00:00)
OS: macOS
```

Jira does not load up, with the error `http: read on closed response body`

Config for JIRA:

   ```
 jira:
      apiKey: "<REDACTED>"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://<REDACTED>.atlassian.net"
      email: "<REDACTED>"
      enabled: true
      position:
        top: 3
        left: 2
        height: 3
        width: 2
      refreshInterval: 900
      project: ["<REDACTED>"]
      username: "<REDACTED>"
      verifyServerCertificate: true
```
