### ISSUE TITLE
Stonks Not Refreshing 

### ISSUE THREAD

**Issue by DeathKhan** [wtfutil/wtf#1075]
Might just be cmdrunner generally, havent tested. but Stonks will not refresh
https://github.com/ericm/stonks
 My config:
```
wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: blue
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    columns: [90,92,90]
    rows: [20,20,20]
  refreshInterval: 1
  updateInterval: 15
  mods:
    AMD:
      type: cmdrunner
      args: ["amd", "--theme", "dot"]
      cmd: "stonks"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshinterval: 1
      updateInterval: 15
      title: AMD
    futs:
      type: cmdrunner
      args: ["ES=f", "--theme", "dot"]
      cmd: "stonks"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshinterval: 1
      updateInterval: 15
      title: /ES
    REI:
      type: cmdrunner
      args: ["REI", "--theme", "dot"]
      cmd: "stonks"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshinterval: 1
      updateInterval: 1
      title: REI
    OIL:
      type: cmdrunner
      args: ["cl=f", "--theme", "dot"]
      cmd: "stonks"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshinterval: 1
      updateInterval: 1
      title: OIL
    Dolla:
      type: cmdrunner
      args: ["DX-Y.NYB", "--theme", "dot"]
      cmd: "stonks" 
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshinterval: 1
      updateInterval: 1
      title: Dollar Index
    BTC:
      type: cmdrunner
      args: ["BTC-USD", "--theme", "dot"]
      cmd: "stonks"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshinterval: 1
      updateInterval: 1
      title: BTC/USD
```
