### ISSUE TITLE
cmdrunner doesn't display the output of tty-clock correctly

### ISSUE THREAD

**Issue by reportaman** [wtfutil/wtf#1091]
## What's broken?

```
cmdrunner:
  args: ["-t""]
  cmd: "tty-clock"
  enabled: true
  position:
    top: 0
    left: 0
    height: 1
    width: 1
  refreshInterval: 1
```

does not display the clock, and instead shows garbled text:

![Screen Shot 2021-07-26 at 1 49 22 PM](https://user-images.githubusercontent.com/71736629/127057327-a50b1d25-5607-4542-8aa7-c33f7d5c3c84.png)
