### ISSUE TITLE
cmdrunner doesn't show proper color (`term` setting not used?)

### ISSUE THREAD

**Issue by albert-ying** [wtfutil/wtf#1267]
## What's broken?
When I run `task burndown.daily` in terminal
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/59846322/176064054-e3c525e4-449b-4805-a91c-748046d76322.png">

In wtfutil

```
    taskburndown:
      args: ["burndown.daily"]
      cmd: "task"
      enabled: true
      position:
        top: 0
        left: 3
        height: 2
        width: 2
      refreshInterval: 30
      type: cmdrunner

```
<img width="733" alt="image" src="https://user-images.githubusercontent.com/59846322/176064223-3964f0a1-9f3c-4dc8-ae83-7c8819d7c950.png">
