### ISSUE TITLE
todoist is not working, api endpoint nolonger available

### ISSUE THREAD

**Issue by rjshrjndrn** [wtfutil/wtf#1417]
## What's broken?

![image](https://user-images.githubusercontent.com/2563385/206425497-6a615454-d591-4ce9-91a8-d94df7a2284a.png)

```
    todoist:
      apiKey: "xxxxxxxxxxxxx"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 20
      projects:
        - xxxxxxx
      refreshInterval: 1h
````
