### ISSUE TITLE
Zendesk Module not showing any tickets

### ISSUE THREAD

**Issue by nhasian** [wtfutil/wtf#1541]
### Steps to Reproduce:

1. create API token in Zendesk
2. add zendesk module to config.yml

```
zendesk:
      apiKey: "1XcUm*********************"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      status: "new"
      subdomain: "mysubdomain"
      username: "username@company.com/token"
```

### Actual Result:

when running wtfutil, the output only displays "No unassigned tickets in queue - woop!!"

### Expected result:

I expected to see a list of tickets with the status of "new"

Additionally, is there a way to filter the results to only show tickets of "new" status that are assigned to a particular group?
