### ISSUE TITLE
Weather module: Weather data is unavailable: no city data

### ISSUE THREAD

**Issue by tolga-balci** [wtfutil/wtf#1586]
Hi Team,

## What's broken?
Following yaml block results in the error below on version 0.43 (latest):
```
   weather_istanbul:
      type: weather
      apiKey: "123apiKey456"
      compact: false
      city_ids:
        - 745042
      enabled: true
      colors: 
        current: "blue"
      position:
        top: 1
        left: 0
        height: 1
        width: 1
    refreshinterval: 1h
    tempUnit: "C"
    useEmoji: false
```

![image](https://github.com/wtfutil/wtf/assets/34794458/9c5af1dc-05df-40d2-a9a5-20312d0d3d76)

Running the curl command with the same parameters returns the weather data correctly:

`
 curl "http://api.openweathermap.org/data/2.5/forecast?id=745042&appid=123apiKey456"
`

Any ideas why that would be the case?

Thanks!
Tolga

PS: FYI, I rm'd the config.yml file and recreated it from scratch, but this did not help.
Edit: added version information.
