### ISSUE TITLE
Yahoo Finance Module shows all zeroe

### ISSUE THREAD

**Issue by ostwalprasad** [wtfutil/wtf#1701]
## What's broken?
Yahoo Finance Module shows all zeroes
![image](https://github.com/user-attachments/assets/14a05364-bb48-434b-baca-772e086936f5)

Config:
```
    yfinance:
      enabled: true
      title: "My Watchlist"
      refreshInterval: 60
      symbols:
        - "^NSEI"
        - "AMD"
        - "ABN.AS"
        - "ICAD.PA"
        - "EURUSD=X"
        - "USDCAD=X"
        - "NIFTY50"
      position:
        top: 2
        left: 3
        height: 1
        width: 1
```
