### ISSUE TITLE
Finnhub is broken

### ISSUE THREAD

**Issue by DestinyStar996** [wtfutil/wtf#1708]
Here's the config ---

```yaml
    finnhub:
      title: "📈 Stock"
      type: finnhub
      enabled: true
      refreshInterval: 10s
      position:
        top: 0
        left: 4
        height: 1
        width: 2
      apiKey: "xxxxxxxx"
      symbols:
        - "AAPL"
```

Rendered empty table:

<img width="598" alt="Image" src="https://github.com/user-attachments/assets/dcd1e2de-531f-449b-ab9b-3e2bc4b51bb5" />
