### ISSUE TITLE
PrettyWeather API Key issue

### ISSUE THREAD

**Issue by danner26** [wtfutil/wtf#171]
#### Summary
PrettyWeather is limiting API calls, stating "2018/06/06 00:01:24 API key has reached calls per day allowed limit" - we need to change this to be a configurable key so everyone can register/install their own API key

##### What is the current behaviour?
PrettyWeather is limiting API calls, stating "2018/06/06 00:01:24 API key has reached calls per day allowed limit" 

##### If the current behavior is a bug, please provide the steps to reproduce it.
![prettyweather](https://user-images.githubusercontent.com/8165027/41002705-965ad02c-68e2-11e8-859f-f58e23c6e687.png)

##### What do you think the expected behaviour should be?
There should be a field in the config that allows us to insert a key to use for PrettyWeather's module

**Comment by senorprogrammer** [comment]
Completely agree.

**Comment by nicholas-eden** [comment]
Does wttr.in accept an api key? It seems like the service the service uses wego internally, with no method of using a client api key to connect to the weather service.  Wego is a go project, it could be ran locally.

**Comment by senorprogrammer** [comment]
I like the idea of switching PrettyWeather to use [wego](https://github.com/schachmat/wego) rather than calling out to a site that then calls wego. I'll investigate how that would work.

**Comment by Boot-Error** [comment]
I would like to take this issue. I'm thinking to use `wego` to fetch the data from any of the backends. Also I'll add extra parameters to setup different backends available in `wego`

**Comment by senorprogrammer** [comment]
Sounds good 👍

**Comment by Seanstoppable** [comment]
Devil's advocate, since wego is a command line tool, you can use CmdRunner to just call it and display it in a widget as is

```
      weather:
        args: ["0"]
        cmd: "wego"
        enabled: true
        type: "cmdrunner"
        position:
          top: 0
          left: 0
          height: 1
          width: 2
        refreshInterval: 100
```

<img width="285" alt="Screen Shot 2019-10-12 at 7 03 39 PM" src="https://user-images.githubusercontent.com/1523955/66708727-3cba6e80-ed23-11e9-9721-53c5d7185142.png">
