### ISSUE TITLE
Bash-snippets integration

### ISSUE THREAD

**Issue by dmitrykdev** [wtfutil/wtf#293]
**Idea**: I think it may be very useful and pretty simple to integrate already implemented CLI tools from [Bash-snippets](https://github.com/alexanderepstein/Bash-Snippets). For example: todo, QRify, stocks, etc.

**Result**: no wheel reinvent

**Comment by senorprogrammer** [comment]
Cool idea. Hadn't heard of bash-snippets before

**Comment by Seanstoppable** [comment]
This seems (largely) covered by cmdrunner for informational items, moreso now that you can run multiple instances at once.

**Comment by senorprogrammer** [comment]
Agreed. I think the documentation for `cmdrunner` should have examples from here to illustrate this. By way of example, here's `stocks` using the new multi-instance format:

```
    bash-stocks:
      args: ["AAPL"]
      cmd: "stocks"
      enabled: true
      position:
        top: 4
        left: 2
        height: 3
        width: 2
      refreshInterval: 5
      type: cmdrunner
```
