### ISSUE TITLE
iStats support

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#297]
#### What problem does this solve?
View [iStats](https://github.com/Chris911/iStats) output in a widget.

#### How do envision it working?

Display the raw output the same way Pretty Weather does.

**Comment by Seanstoppable** [comment]
Here is a config for istats:

Height of 1 cuts off some of the battery stats for me.

```
    istats:
      args: ["all"]
      cmd: "istats"
      enabled: true
      type: "cmdrunner"
      position:
        top: 0
        left: 3
        height: 2
        width: 2
      refreshInterval: 1
```

![image](https://user-images.githubusercontent.com/1523955/57184405-0382f600-6e89-11e9-981a-d2f0f57882f4.png)
