### ISSUE TITLE
Does it work on Cygwin?

### ISSUE THREAD

**Issue by E3V3A** [wtfutil/wtf#350]
and if not what is needed and required to make it work on Windows?

**Comment by senorprogrammer** [comment]
Some people are running it on Windows (a few modules have Windows-specific implementations for them). No idea if it'll work on Cygwin, I've never used that. Give it a build and if it doesn't work for you, feel free to create tickets for any issues you find.

**Comment by christianboyle** [comment]
I can confirm it does work on Cygwin (go1.11.1 windows/amd64) with the build steps listed in the install docs. It generates wtf.exe after make run. Double-click that puppy and you're good to go.

![1](https://user-images.githubusercontent.com/1605754/52017940-73f73100-24ae-11e9-9612-30655c3d4215.png)

**Comment by senorprogrammer** [comment]
Thanks @christianboyle, much appreciated.

**Comment by E3V3A** [comment]
@christianboyle 
I can't get this to work with the MSI on Cygwin. 
The GOPATH is getting butchered when running `go get -u ...` into:
```
$ go get -v -u github.com/wtfutil/wtf
github.com/wtfutil/wtf (download)
# cd .; git clone https://github.com/wtfutil/wtf C:\Users\XXXX\go\src\github.com\wtfutil\wtf
Cloning into 'C:\Users\XXXX\go\src\github.com\wtfutil\wtf'...
fatal: Invalid path '/cygdrive/c/C:\Users\XXXX\go\src\github.com\wtfutil\wtf': No such file or directory
package github.com/wtfutil/wtf: exit status 128
```

1. How did you install your GO version? 
2. Did you use the MSI or did you compile from sources?
3. Are you using the Cygwin (Bash + Mintty) shell or something else?

**Comment by E3V3A** [comment]
@christianboyle 
Hmm, starnge. I have the exact same `go env` as you do, except I don't have such a nice Zsh as you do.
(How did you set that up? For some reason my Zsh can't handle colors... )

1. What exact git version are you using?
2. Where/How did you install it?

**Comment by christianboyle** [comment]
@E3V3A 

1. 2.17.0
2. https://github.com/robbyrussell/oh-my-zsh and https://github.com/sindresorhus/pure

**Comment by E3V3A** [comment]
So you are using the default Cygwin git!? -- Ok that is good news!

The second good news is that I got it to work with the Administrator Windows `CMD`:
```cmd
cd C:\Users\XXXX\go
go get -v -u github.com/wtfutil/wtf

github.com/wtfutil/wtf (download)
github.com/wtfutil/wtf/vendor/golang.org/x/text/encoding/internal/identifier
...
# BOM There it is!
```

**However**, trying the same in Cygwin Mintty, PowerShell, PWSH, Zsh, doesn't quite work.

The 3rd good news, is that on a 100th trial, I managed to set the GOPATH to something that was *seemingly* accepted by the `go get`:

```bash
# Note the ";"
export GOPATH=";C:\Users\XXXX\go"
go get -v -u github.com/wtfutil/wtf

  github.com/wtfutil/wtf (download)
  github.com/wtfutil/wtf (download)
```

Why 2 times ?  and not like in CMD??
Now set it back...and go on.
```
export GOPATH="C:\Users\XXXX\go"
cd ./src/github.com/wtfutil/wtf/
$ make install
go clean
go install -ldflags="-s -w -X main.version=0.4.0-66-gab0dde -X main.date=2019-02-02T03:03:40+0200"
which wtf
...
```

But unfortunately `make run` fails:
```
$ make run
go build -o bin/wtf
bin/wtf
C:\Users\XXXX\.config\wtf\config.yml
Error: character set not supported
make: *** [Makefile:35: run] Error 1
```

What character set is that!?  

BUT it seem that the exe was built anyway... Very confusing.

```bash
/cygdrive/c/Users/XXXX/go/bin
$ ./wtf.exe
C:\Users\XXXX\.config\wtf\config.yml
Error: character set not supported
```

What's in this file:
```yml
# cat ../../.config/wtf/config.yml

wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Avignon: "Europe/Paris"
        Barcelona: "Europe/Madrid"
        Dubai: "Asia/Dubai"
        Vancouver: "America/Vancouver"
        Toronto: "America/Toronto"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    security:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    status:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 1
    system:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    textfile:
      enabled: true
      filePath: "~/.config/wtf/config.yml"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
```
