### ISSUE TITLE
Cannot get CMDrunner to display

### ISSUE THREAD

**Issue by Hamspiced** [wtfutil/wtf#384]
#### What problem are you having and how can we help?
I simply cannot get CMDRunner to work at all.

I have the rest of the dashboard setup fine.

However i cannot get the Cmdrunner module to display at all.  even by itself.  WTF runs and loads and doesnt throw any error.  it just doesnt display anything.

    cmdrunner:
        args: ["www.google.com"]
        cmd: "ping"
        enabled: true
        position:
        top: 2
        left: 5
        height: 2
        width: 3
        refreshInterval: 300

**Comment by senorprogrammer** [comment]
The problem with using `ping` for this is that it never really returns the process until you kill it. It just runs forever and never dumps the output by default. If you change your args to `["-c3", "www.google.com"]` you'll see that at least it now displays output because the process terminates after pinging three times.

**Comment by senorprogrammer** [comment]
Turns out no matter what command is used, the widget doesn't show up at all. Re-opening until resolution.

**Comment by E3V3A** [comment]
@Hamspiced  
What OS are you running on?
If it is Windows, you don't have `ping`, you have `PING.EXE`. Not sure the code is taking this into consideration...

**Comment by E3V3A** [comment]
```bash
# This is the correct PowerShell code (if Windows PATH is correct)
PING.EXE -n 3 google.com
```

Thus the cmdrunner Widget [execution code](https://github.com/wtfutil/wtf/blob/master/cmdrunner/widget.go#L53) must be equivalent to: 
```go
//cmd := exec.Command(widget.cmd, widget.args...)
cmd := exec.Command("PING.EXE", "-n", "3", "google.com")
```
(Pulled from the top of my head without testing.)

**Comment by Hamspiced** [comment]
> ```shell
> # This is the correct PowerShell code (if Windows PATH is correct)
> PING.EXE -n 3 google.com
> ```
> 
> Thus the cmdrunner Widget [execution code](https://github.com/wtfutil/wtf/blob/master/cmdrunner/widget.go#L53) must be equivalent to:
> 
> ```go
> //cmd := exec.Command(widget.cmd, widget.args...)
> cmd := exec.Command("PING.EXE", "-n", "3", "google.com")
> ```
> 
> (Pulled from the top of my head without testing.)

OSX, Maybe its my config.  IDK at this point, because some of the newer widgets that have been added i cannot get to display either, like the Spotify one.

**Comment by senorprogrammer** [comment]
If you want to email me your config, I'll give it a try: chriscummer@me.com

Be sure to remove any API keys, etc. that might be in it.

**Comment by senorprogrammer** [comment]
Found it. It's an indenting issue. Your config has the following:
```
    cmdrunner:
        args: []
        cmd: "uptime"
        enabled: true
        position:
        top: 1
        left: 9
        height: 1
        width: 4
        refreshInterval: 300
```
but it needs to be
```
    cmdrunner:
        args: []
        cmd: "uptime"
        enabled: true
        position:
          top: 1
          left: 9
          height: 1
          width: 4
        refreshInterval: 300
```
I've opened https://github.com/wtfutil/wtf/issues/389 to improve this.
