### ISSUE TITLE
Enabled widgets with invalid positions should raise an error

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#389]
#### What's the problem?
If the `position` data is malformatted a widget will silently fail to show up:
```
    cmdrunner:
        args: []
        cmd: "uptime"
        enabled: true
        position:
        top: 1
        left: 9
        height: 1
        width: 4
        refreshInterval: 300
```

#### How did you expect it to behave?
This is effectively the same as `height: 0; width: 0` which should be treated as invalid. If a widget is enabled it must have a height/width minimum of 1.

If the widget is `enabled` and if the position is `invalid`, then raise an error and do not load.
