### ISSUE TITLE
why does my wtfutil always abnormal exit?

### ISSUE THREAD

**Issue by tabris233** [wtfutil/wtf#397]
#### What's the problem?

My wtfutil always abnormal exit when it's running.

When I use the command,wtfutil,it will abnormal exit in a few seconds or some hours.

![](https://files.gitter.im/wtfutil/Lobby/k0WQ/__________20190305145240.png)

#### How did you expect it to behave?

I expect it won't abnormal exit.

#### Operating system 

manjaro-deepin 

#### Terminal program & version
deepin-terminal 
zsh 5.7.1-1
tmux 2.8

#### WTF version
0.4.0

**Comment by E3V3A** [comment]
* What's abnormal about it?
* What did you expect it to be?
* How can we reproduce it?

**Comment by tabris233** [comment]
> * What's abnormal about it?
My wtfutil always abnormal exit when it's running.
When I use the command,wtfutil,it will abnormal exit in a few seconds or some hours.
> * What did you expect it to be?
I expect it won't abnormal exit.
> * How can we reproduce it?
I don't know.   Maybe you need to install the same environment as mine.
At first,i think someone maybe has the same problem like me , So I talk it in gitter group. 
I didn't try to analyze it. 

@E3V3A 
Thanks for you watch my issue.
I re-edit this issue.

**Comment by tabris233** [comment]
this is my config.yml
```yml
wtf:
  colors:
    background: 
    border:
      focusable: darkslateblue
      focused: orange
      normal: "Light Gray"
  grid:
    columns: [28, 35,40,30]
    rows: [9, 10,4]
  refreshInterval: 1
  openFileUtil: open 
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Avignon: "Europe/Paris"
        Barcelona: "Europe/Madrid"
        Dubai: "Asia/Dubai"
        Vancouver: "America/Vancouver"
        Toronto: "America/Toronto"
        Shanghai: "Asia/Shanghai"
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    # security:
    #   enabled: true
    #   position:
    #     top: 1
    #     left: 0
    #     height: 1
    #     width: 1
    #   refreshInterval: 3600
    status:
      enabled: false
      position:
        top: 2
        left: 0
        height: 1
        width: 3
      refreshInterval: 1
    # system:
    #   enabled: true
    #   position:
    #     top: 0
    #     left: 1
    #     height: 1
    #     width: 1
    #   refreshInterval: 3600
    textfile:
      enabled: false
      filePath: "~/.config/wtf/config.yml"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
    # bamboohr:
    #   apiKey: "3276d7155dd9ee27b8b14f8743a408a9"
    #   enabled: false
    #   position:
    #     top: 1
    #     left: 1
    #     height: 1
    #     width: 1
    #   refreshInterval: 900
    #   subdomain: "testco"
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 3
        height: 3
        width: 1
      refreshInterval: 1
    prettyweather:
      enabled: true
      city: "Harbin"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      unit: "c"
      view: 0
      language: "zh"
    git:
      commitCount: 1
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: false
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 8
      repositories:
      - "/home/tabris/work/code/blog"
    cmdrunner:
      args: ["-c3","www.google.com"]
      cmd: "ping"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      refreshInterval: 300
      name: "asd"
    resourceusage:
      enabled: false
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 1
    bargraph:
      enabled: false
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 1
    textfile:
      enabled: false
      position:
        top: 2
        left: 3
        height: 1
        width: 1
      refreshInterval: 1
    ipinfo:
      colors:
        name: orange
        value: white
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 150
    gitter:
      apiToken: "ab345546asdfasb465234fgjgh068f39a35c3e4139ee383f7"
      enabled: false
      numberOfMessages: 10
      position:
        top: 4
        left: 1
        height: 1
        width: 4
      roomUri: wtfutil/Lobby
      refreshInterval: 300
    power:
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
```
