### ISSUE TITLE
The filePath value for textfile should be dynamic

### ISSUE THREAD

**Issue by MahmoudDolah** [wtfutil/wtf#554]
## What should it do?
I keep a [daily logbook](https://gist.github.com/MahmoudDolah/8cfbf6f652801e0e601b998ec2a15078#file-logbook-L2-L7) and I would like for the `filePath` to support this since the file I would like to see in the dashboard would be different everyday

**Comment by senorprogrammer** [comment]
I'm not clear on what you mean by this. How would this look?

**Comment by MahmoudDolah** [comment]
My idea is that for filePath, you could put something like
```
textfile:
  enabled: true
  filePaths:
  - "~/Documents/logbook/$(date '+%Y-%m-%d').md"                   <- This here
  format: true
  formatStyle: "dracula"
  position:
    top: 5
    left: 4
    height: 2
    width: 1
  refreshInterval: 15
  wrapText: true
```
And the file it would show in the widget would update (when refreshed) based on the evaluated expression
Instead of me manually updating my `config.yml` everyday to show today's logbook entry, I would like for me to automate this

Sorry my original comment wasn't clear enough. Does this make more sense?
Also, thanks for making such a fantastic tool!
