### ISSUE TITLE
Does the gitlab module support self hosted gitlab instances?

### ISSUE THREAD

**Issue by MatanRubin** [wtfutil/wtf#558]
Or does it support only projects hosted on gitlab.com?

**Comment by zapp42** [comment]
Works with self-hosted, too. You have to set the domain parameter to the URL of your gitlab instance.

**Comment by MatanRubin** [comment]
Interesting. I tried setting the domain as you suggested but couldn't get it to work.
I didn't see any errors - just the projects did not show any MRs (although I know some MRs exist).

Just to make sure, when defining the projects, the key should be the project name and the value should be the group name or username? The documentation says the value should be the "namespace", I interpreted that to mean "group name". Please correct me if I misinterpreted.

**Comment by thommor** [comment]
Just set this up this morning and works fine for me.

Yes the namespace is the group name/username depending if the project is in a group or not.

**Comment by zapp42** [comment]
Hmm... As it turns out, it does not work for me. I thought it was working because the widget showed up w/o errors and my test project did not have any MRs or stars. :(

Anyway, from looking at the code the domain needs to have the api url (e.g. https://your-gitlab/api/v4) and the projects must look like this (for a project "this/is/a/nested/example"):
projects:
   example: "this/is/a/nested"

@thommor can you confirm?

Still does not work for me though.

**Comment by thommor** [comment]
Mine looks like this:

```
gitlab:
      apiKey: "*****************"
      enabled: true
      domain: https://gitlab.dev.local/
      position:
        top: 3
        left: 1
        height: 2
        width: 2
      refreshInterval: 1
      projects:
        some-managedservice: "some-group"
      username: "thommor"
```

Renamed projects, domain etc but works fine.

<img width="746" alt="Screenshot 2019-08-29 at 10 57 00" src="https://user-images.githubusercontent.com/45167957/63930723-cb14b280-ca4b-11e9-87c0-fc06c3b7523d.png">
