### ISSUE TITLE
Can we overwrite port number on transmission module

### ISSUE THREAD

**Issue by 0xF61** [wtfutil/wtf#565]
According to source code of transmission it is harcoded to use 9091 port for rpc protocol. How can I overwrite port number on config.yml. According to source code it can be achievable but seems not workin.

```
... some other configs ^^^
    transmission:
      enabled: true
      host: "nas.home"
      port: 9092
      position:
        top: 2
        left: 2
        width: 1
        height: 1
      refreshInterval: 3
```
