### ISSUE TITLE
How do I add projects with the same name for the GitLab module?

### ISSUE THREAD

**Issue by AndrewCarterUK** [wtfutil/wtf#566]
## How can we help?

The documentation uses a key value pair, where the key is the name of the repository and the value is the namespace.

We have a few projects that use `api` as a slug for the name, and are differentiated by their namespace.

For example:

`gitlab.com/our-company/customer-1/shopping-site/api`
`gitlab.com/our-company/customer-2/phone-app/api`

With the GitLab module, these both have a key of `API` so can't be represented in YAML (I think?).

**Comment by senorprogrammer** [comment]
Yeah, this is definitely problematic. I think a better approach would be to have:
```
    projects:
      namespace-a:
      - project-name-1
      - project-name-2
      namespace-b:
      - project-name-1
      - project-name-3
```

**Comment by AndrewCarterUK** [comment]
I managed to find a workaround, as I can do:

```yml
projects:
    "customer-1/shopping-site/api": "our-company"
    "customer-2/phone-app/api": "our-company"
```

But it feels a bit messy!
