### ISSUE TITLE
Restore option to set background and text color on a module basis

### ISSUE THREAD

**Issue by amcooper** [wtfutil/wtf#568]
## What's broken?
Feature request #307 , which was to allow configuring background and text colors by module, and which was implemented in pull request #320 , has regressed. 
A config written as below will not render the module colors as expected.
```
# config.yml
# [snip]
  mods:
    battery:
      type: power
      title: "⚡️"
      enabled: true
      colors:
        background: "white"
        text: "black"
# [snip]
```
