### ISSUE TITLE
Using pipes in cmdrunner/ Using alias in cmdrunner

### ISSUE THREAD

**Issue by patillacode** [wtfutil/wtf#610]
## What's broken?
I think cmdrunner doesn't allow the use of pipes nor aliases, at least I haven't been able to make it happen.

As an example:
Running `ps auxc | head -5` in my terminal gives me the desired output:
```
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
dvitto             582  22.6  4.0  7536028 1168416   ??  S    Sat12AM 526:21.12 iTerm2
_windowserver      194  10.0  0.9  9565768 265948   ??  Ss   Sat12AM 760:16.23 WindowServer
dvitto            3781   5.4  0.8  6950944 229216   ??  S    Wed09PM 158:42.63 ts3client_mac
_coreaudiod        152   3.6  1.2  7010128 340860   ??  Ss   Sat12AM 428:09.19 coreaudiod
```

But i cannot manage to make this happen within the `cmdrunner` mod, I have tried several ways:

```
processes:
      args: ["auxc", "|",  "head", "-5"]
      cmd: "ps"
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 30
      title: "Processes"
      type: cmdrunner
```

OR

```
processes:
      args: []
      cmd: "ps auxc | head -5"
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 30
      title: "Processes"
      type: cmdrunner
```

Output is always: `exit status 1`

When I set a function in the `~/.zshrc` file, like:
```
psps () {
	ps auxc | head -5
}
```

It works when used in the terminal, but when trying from the `cmdrunner` like this:

```
processes:
      args: []
      cmd: "psps"
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 30
      title: "Processes"
      type: cmdrunner
```

In this case the output is: `exec: "psps": executable file not found in $PATH`

I also tried aliasing the command and creating a function in my `~/.zshrc` file without luck.

Am I missing something?
I haven't found yet one example that uses pipes or aliases/functions

Thanks in advance and congratulations for an awesome tool :)
