### ISSUE TITLE
Colors won't work for cmdrunner when using nodejs chalk or colorette library

### ISSUE THREAD

**Issue by abhayjatindoshi** [wtfutil/wtf#618]
## What's broken?
Colors won't work for cmdrunner when using nodejs chalk or colorette library

**Comment by senorprogrammer** [comment]
See this issue for more details on why this is: https://github.com/wtfutil/wtf/issues/577

**Comment by abhayjatindoshi** [comment]
I tried giving FORCE_COLOR=1 as env variable but it seems chalk and colorette both failed to give NC character after they had it coloured. It'll be great if this is supported from cmdrunner instead. As both the libraries detects no support for color but on the other hand if I check for iTerm.app it seems to detect 256-bit color support for my current configuration.

**Comment by Seanstoppable** [comment]
@abhayjatindoshi Can you give more details on how you are using this? I.e. what is your config?

Have you tried wrapping this in a shell script and setting `FORCE_COLOR=1` in that? CmdRunner probably doesn't use any environment variables passed to `wtf`

**Comment by abhayjatindoshi** [comment]
I tried to run the node script wrapped in a shell file as below.

```sh
# ~/temp.sh
export FORCE_COLOR=1
node ~/folder-path/index.js arguments
```
When I execute temp.sh on iTerm.app it gives the expected output. 
![image](https://user-images.githubusercontent.com/19318032/64487917-831d3900-d25e-11e9-8d06-17de032edabc.png)

Even on Terminal.app it works well like below
![image](https://user-images.githubusercontent.com/19318032/64487972-4e5db180-d25f-11e9-8920-aec20403e475.png)

But when I execute that file on wtfutil as I said before the NOCOLOR char doesn't work. so even the :: are getting coloured like below.
![image](https://user-images.githubusercontent.com/19318032/64487979-69c8bc80-d25f-11e9-9541-4adb85ee3201.png)

This is my configuration on config.yml for cmdrunner
```yml
    cmdrunner_web:
      type: 'cmdrunner'
      title: '⬆️ ⬇️'
      cmd: 'sh'
      args: ["/Users/mac-name/temp.sh"]
      enabled: true
      position: 
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 5
```

@Seanstoppable
