### ISSUE TITLE
feedreader: allow multiple instances

### ISSUE THREAD

**Issue by lggomez** [wtfutil/wtf#633]
## What should it do?
Allow multiple instances of the feedreader module, as it does with cmdreader. If it is plausible and someone can give me a quick rundown of the needed changes I may give it a try

**Comment by senorprogrammer** [comment]
You should be able to have as many as you want, just define the `type` attribute. Example:
```
  wtfutil:
      enabled: true
      feeds:
      - http://wtfutil.com/blog/index.xml
      feedLimit: 10
      position:
        top: 2
        left: 2
        width: 1
        height: 1
      updateInterval: 14400
    type: feedreader
    hackernews:
      enabled: true
      feeds:
      - https://news.ycombinator.com/rss
      feedLimit: 10
      position:
        top: 3
        left: 4
        width: 1
        height: 1
      updateInterval: 14400
    type: feedreader
```
