### ISSUE TITLE
colors.description in Google calendar changes colour of time in the event's title

### ISSUE THREAD

**Issue by indradhanush** [wtfutil/wtf#638]
## What's broken?
`colors.description` in Google calendar changes colour of time in the event's title.

For example, with the following configuration, where `title` is `orange` and `description` is `white`:
```
    gcal_0:
      type: gcal
      colors:
        title: "orange"
        description: "white"
        highlights:
        - ['Engineering team daily', 'lightblue']
```
![s_2019-09-16_170726](https://user-images.githubusercontent.com/2682729/64955263-6956a400-d8a5-11e9-8616-62d470e72de3.png)

And when I change the description to `grey`, I have:

![s_2019-09-16_170700](https://user-images.githubusercontent.com/2682729/64955372-b33f8a00-d8a5-11e9-938f-db9a7d15e1ce.png)

There could be two possible approaches to fix this:

1. Leave the time of the event to a neutral color independent of `title` and `description`.
2. Set the color of time of the event to the same as that of the `title`.

Additionally, if we choose to go with `1.` above, maybe we can add a `colors.event_time` to allow for customizing the time of the event, independent of this issue. 

I'd be happy to dig into the code and try fixing this if this sounds reasonable and we can decide what approach would be best. :slightly_smiling_face:
