### ISSUE TITLE
Clocks doesn't support global row color

### ISSUE THREAD

**Issue by kusold** [wtfutil/wtf#658]
## What's broken?
Clock doesn't respect the global `colors.rows.even/odd`

## Screenshot
![image](https://user-images.githubusercontent.com/509966/65646399-3785c180-dfb8-11e9-8e6c-5bc2fcf2c100.png)

## Reproduction Config
```yaml
wtf:
  colors:
    rows:
      even: red
      odd: purple
  mods:
    clocks:
      enabled: true
      position:
        top: 0
        left: 0
        width: 1
        height: 1
      locations:
        New York: 'America/New_York'
        Chicago: 'America/Chicago'
        Denver: 'America/Denver'
```
