### ISSUE TITLE
GitHub Module - Incorrect Issue Stats

### ISSUE THREAD

**Issue by alexfornuto** [wtfutil/wtf#693]
## What's broken?
The `Issues` stat reported by the GitHub module don't match what GitHub itself tells me.

## Example
Compare:
![image](https://user-images.githubusercontent.com/2349184/66662174-f32c2f80-ec0d-11e9-8354-9c1bd6181d89.png)

To:
![image](https://user-images.githubusercontent.com/2349184/66662243-1060fe00-ec0e-11e9-91be-1132f63063a7.png)

Note that this project has 46 open issues, and the module is reporting 62.

### OS
Fedora 30, kernel `5.2.17-200.fc30.x86_64`

### App Config

```bash
wtfutil --version
v0.20.0-330-g6266ed
```

```yml
   github:
      apiKey: "REDACTED"
      baseURL: ""
      customQueries:
        othersPRs:
          title: "Others Pull Requests"
          filter: "is:open is:pr"
      enabled: true
      enableStatus: true
      position:
        top: 1
        left: 0
        height: 2
        width: 2
      refreshInterval: 300
      repositories:
        - "pantheon-systems/documentation"
        - "alexfornuto/.dotfiles"
      uploadURL: ""
      username: "alexfornuto"
```

Note that the other repo I'm tracking has `0` issues, so it's not adding both into one stat.
