### ISSUE TITLE
Gitlab HTTP errors spamming over content

### ISSUE THREAD

**Issue by Ameobea** [wtfutil/wtf#716]
![](https://ameo.link/u/6o6.png)

For some reason, the Gitlab module regularly dumps HTTP errors to stdout which overwrites other modules.  I've tracked this down and found that it originates from within the third-party Gitlab go library which is being used for the module.  I managed to work around this by explicitly setting the go standard logger to route logs to /dev/null, but this has the side effect of supressing the output of `log.Fatalf` calls which contain debug info useful for tracking down issues.

I don't know if it's my Gitlab config in particular which is problematic, but here it is just in case:

```yml
wtf:
  mods:
    gitlab_website:
      type: 'gitlab'
      apiKey: 'secret'
      enabled: true
      position:
        top: 0
        left: 2
        height: 4
        width: 1
      refreshInterval: 300
      projects:
        website: 'stackline-dev'
      username: 'cprimozic'
    gitlab_api:
      type: 'gitlab'
      apiKey: 'secret'
      enabled: true
      position:
        top: 0
        left: 3
        height: 4
        width: 1
      refreshInterval: 300
      projects:
        api: 'stackline-dev'
      username: 'cprimozic'
    gitlab_search_service:
      type: 'gitlab'
      apiKey: 'secret'
      enabled: true
      position:
        top: 0
        left: 4
        height: 4
        width: 1
      refreshInterval: 300
      projects:
        search-service: 'stackline-dev'
      username: 'cprimozic'
```
