### ISSUE TITLE
wrong alignment when sum of columns or rows is less than rows and columns of terminal

### ISSUE THREAD

**Issue by artee666** [wtfutil/wtf#774]
Having such simple config:

```
wtf:
  grid:
    columns: [20]
    rows: [3]
  refreshInterval: 1
  mods:
    uptime:
      type: cmdrunner
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 30
```
And terminal which is wider than 20 chars and higher than 3 rows, the box would be aligned bottom right, instead of top left.
It was working in 0.19.
