### ISSUE TITLE
project id in todoist module can't be greater than 2147483647

### ISSUE THREAD

**Issue by tykazzz** [wtfutil/wtf#781]
Int32 in golang max value is 2147483647, my todoist project id is bigger and wtfutil crashes when I add this project in config
```
Error: Unsupported map value: 
map[interface {}]interface {}{"colors":map[interface {}]interface {}{"border":map[interface {}]interface {}{"focusable":"darkslateblue", "focused":"orange", "normal":"gray"}}, "grid":map[interface {}]interface {}{"columns":[]interface {}{32, 32, 32, 32, 90}, "rows":[]interface {}{10, 10, 10, 4, 4, 90}}, "mods":map[interface {}]interface {}{"todoist":map[interface {}]interface {}{"apiKey":"29238tne9dm******92je3ld9k39ddk", "enabled":true, "position":map[interface {}]interface {}{"height":4, "left":0, "top":0, "width":3}, "projects":[]interface {}{2147483648}, "refreshInterval":10}}, "refreshInterval":1}
```

**Comment by senorprogrammer** [comment]
Thanks for reporting this. I should have a fix on `master` shortly.

**Comment by senorprogrammer** [comment]
I don't think that's your problem. I have two Todoist project IDs in my config that are larger than 2147483647 (both of mine start with `217*******`). We're also defining `int` so it should be defaulting to `uint32` or `uint64` under the hood, both of which are plenty large. I suspect you have a configuration issue.

Feel free to paste your Todoist config here, redacting your `apiKey` and `projects` values.

**Comment by tykazzz** [comment]
```
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: blue
      normal: gray
  grid:
    columns: [23, 21, 15, 34, 20, 15]
    rows: [11, 11, 11, 9, 12]
  refreshInterval: 1
  #term: "xterm-256color"
  mods:
    todoist: 
      apiKey: ""
      enabled: true
      position: 
        height: 4
        left: 0
        top: 0
        width: 3
      projects: 
        - 2221111111
      refreshInterval: 10
```
that is my config, it works on ubuntu 19.04 (64bit), but not on raspbian, (armv7l), wtf crashes when project id is greater than 2147483647
