### ISSUE TITLE
Inverted text not properly displayed

### ISSUE THREAD

**Issue by pacien** [wtfutil/wtf#860]
## What's broken?

```yaml
wtf:
  # ...
  mods:
    test:
      title: Test
      enabled: true
      type: cmdrunner
      cmd: echo
      args: ["Normal \e[7minverted \e[27mNormal"]
      position:
        # ...
```

is rendered as

![15840458568758](https://user-images.githubusercontent.com/1449319/76565330-a1cce880-64aa-11ea-92b1-d4dd611c2149.png)

instead of

![15840459109691](https://user-images.githubusercontent.com/1449319/76565391-c32dd480-64aa-11ea-9778-258875a8e119.png)

(in the same terminal emulator (alacritty))
