### ISSUE TITLE
Can we have multiple instance of the same module

### ISSUE THREAD

**Issue by Tdnshah** [wtfutil/wtf#881]
## I what to know?
I want to know in WTF dashboard can we have multiple instance of the the same module like i want to have 3 different todo lists one for my personal use, one for my office use, and one for tracking the contributions i do to opensource project?

Similarly for the trello board for each board i want to have a different instance in my dashboard can i have something like this?

**Comment by Seanstoppable** [comment]
You can indeed! I can't believe we failed to make this clear in the documentation, but you can see an example here: https://wtfutil.com/modules/cmdrunner/brew_outdated/
Essentially, you can give any config a name as long as you specify the module type and have multiple running at the same time.

**Comment by senorprogrammer** [comment]
That's a good point. I don't think the process for running multiple instances of a widget is documented anywhere. I've created this issue to handle that: https://github.com/wtfutil/wtfdocs/issues/89

**Comment by Tdnshah** [comment]
Thank you for the reply @Seanstoppable  I tried the same for the todo module but it didnt worked can you please guide where am i going wrong . @senorprogrammer  thanks for creating an issue in docs once i understand this ill like to contribute back so ill resolve the issue once i get the answer for the same.
Thank you

**Comment by senorprogrammer** [comment]
Here's how to configure for multiple `todo` instances:

```
    todo:
      enabled: true
      filename: "todo1.yml"
      focusChar: 1
      position:
        top: 0
        left: 1
        height: 2
        width: 2
      refreshInterval: 3600
      type: todo
    todo2:
      enabled: true
      filename: "todo2.yml"
      focusChar: 2
      position:
        top: 2
        left: 3
        height: 2
        width: 2
      refreshInterval: 3600
      type: todo 
```
