### ISSUE TITLE
Clocks: sort in order specified

### ISSUE THREAD

**Issue by OJFord** [wtfutil/wtf#896]
## What should it do?
```
clocks:
  locations:
    London: 'Europe/London'
    GMT: 'GMT'
```

Currently (with London on BST) there would be no way to get those displayed in the order specified. `sort: alphabetical` and `sort: chronological` will both put GMT first.

While asc/descending sort might be nice, what I'm actually requesting is `sort: as-written`, and hoping that that order is preserved by the yaml parser you're using (since it's not an array, I think the spec allows it not to be).

I'd go so far as to say 'as-written' sorting would be the most obvious default, too.
