### ISSUE TITLE
cmd runner not working as expected

### ISSUE THREAD

**Issue by GideonWolfe** [wtfutil/wtf#912]
## What's broken?

I have tried a couple times to incorporate commands I run in the terminal to `cmdrunner` widgets without success.

1. First example, `iponmap`. `iponmap` takes a list of IP addresses and displays them on a map in the terminal.

I have a script that goes

```curl -s 'http://some.site/api...' | jq 'some json parsing' | iponmap```

![jfmap](https://user-images.githubusercontent.com/32942052/83431541-544a8280-a3ec-11ea-812a-3f97cb0b3e2a.png)

When I try to run this script from a `cmdrunner` widget, the widget is simply blank, no errors or anything.

2. `ghcal` prints a text representation of your github contributions into the terminal. When I run `ghcal --no-ansi` in my shell, I get

```
╔═══════════════════════════════════════════════════════════════════════════════════════════════╗
║        Aug       Sep     Oct     Nov       Dec     Jan     Feb       Mar     Apr     May      ║
║Sun   ⬚ ▤ ▤ ▢ ⬚ ⬚ ▢ ⬚ ⬚ ▢ ⬚ ▢ ▢ ▢ ⬚ ⬚ ⬚ ▢ ▢ ⬚ ⬚ ⬚ ⬚ ⬚ ▤ ▢ ▢ ▢ ⬚ ▢ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ◼ ▢ ▣ ⬚ ⬚ ▢ ▢║
║Mon   ⬚ ▢ ⬚ ⬚ ⬚ ▢ ▢ ▢ ⬚ ▢ ⬚ ◼ ⬚ ▢ ⬚ ⬚ ▢ ▢ ⬚ ▢ ⬚ ⬚ ⬚ ⬚ ▣ ▢ ▢ ⬚ ▢ ▢ ⬚ ⬚ ⬚ ⬚ ⬚ ▢ ▤ ▢ ▣ ▢ ▢ ⬚ ⬚ ⬚ ▢║
║Tue   ⬚ ▢ ▢ ▢ ▢ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ◼ ⬚ ▢ ▢ ⬚ ⬚ ▢ ⬚ ▢ ▢ ▢ ⬚ ⬚ ⬚ ▢ ▢ ▢ ⬚ ▢ ⬚ ▢ ⬚ ⬚ ▢ ▢ ▤ ⬚ ▢ ▤ ⬚ ▢ ▢ ⬚ ⬚║
║Wed   ▢ ⬚ ⬚ ▢ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ⬚ ▤ ▢ ⬚ ⬚ ▢ ⬚ ⬚ ▢ ▢ ▢ ⬚ ⬚ ▢ ▢ ▢ ▢ ⬚ ⬚ ▢ ⬚ ⬚ ▢ ⬚ ▢ ▢ ◼ ⬚ ▤ ▢ ▢ ⬚ ⬚ ⬚ ▢║
║Thu   ▢ ▢ ⬚ ▢ ⬚ ▢ ⬚ ⬚ ⬚ ▢ ▢ ▣ ▢ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ▢ ⬚ ▢ ▢ ▢ ▢ ⬚ ▢ ▢ ▢ ▢ ▢ ⬚ ⬚ ⬚ ▢ ▢ ▢ ▣ ▢ ▢ ▤ ▢ ▢ ⬚ ▢║
║Fri   ▢ ⬚ ▢ ⬚ ⬚ ▢ ⬚ ⬚ ▢ ▢ ▢ ⬚ ▢ ⬚ ⬚ ⬚ ▢ ▢ ▢ ⬚ ⬚ ▢ ⬚ ▤ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ▢ ⬚ ▢ ▢ ▤ ⬚ ▢ ⬚ ▢ ▢║
║Sat   ▣ ⬚ ▢ ⬚ ⬚ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ▢ ▢ ▢ ▢ ▢ ▢ ▢ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ⬚ ⬚ ⬚ ▢ ⬚ ⬚ ⬚ ⬚ ▢ ▢ ⬚ ⬚ ▢ ▢ ▢║
║* * *                                                                                          ║
║Commits in Jul 21, 2019 – May 30, 2020: 782                                                    ║
║Longest Streak: 16 days                                                                        ║
║Current Streak: 4 days                                                                         ║
║Max a day: 56                                                                                  ║
╚═══════════════════════════════════════════════════════════════════════════════════════════════╝
```

But when I try to run this command in a wtf `cmdrunner`, the window just says "exit status 1", which I have never gotten from just running the command.

Here is how I am trying to launch it

```yaml
wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: blue
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    columns: [33, 33, 33]
    rows: [20, 20, 20, 20, 20, 20, 20, 20]
  refreshInterval: 1
  
  mods:
    githubcal:
      type: cmdrunner
      args: ["--no-ansi"]
      cmd: "ghcal"
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 3
      refreshinterval: 30
      title: "🤖 Tech"
```
