### ISSUE TITLE
How to write a todo.yml file?

### ISSUE THREAD

**Issue by Rosanse** [wtfutil/wtf#917]
## How can we help?
I donnot know how to write a todo.yml.   

Could someone help me? Or give me an example.  
Thx.

**Comment by senorprogrammer** [comment]
Can you give me a bit more info? I assume this is for the Todo module? You should be able to configure the module in your `config.yml` file like so (this is mine):
```
    todo:
      enabled: true
      filename: "todo.yml"
      focusChar: 1
      position:
        top: 0
        left: 1
        height: 2
        width: 2
      refreshInterval: 3600
      type: todo
```
and WTF will handle creating the actual `todo.yml` file for you. You shouldn't have to create the `todo.yml` file yourself.
