### ISSUE TITLE
Trouble executing .sh script.

### ISSUE THREAD

**Issue by HoverBaum** [wtfutil/wtf#989]
## How can we help?

My goal is to display an ASCII based time, so that I can get a big current time on my dashboard. For that I want to execute `date '+%H:%M' | sed -e 's/\(.\)/\1 /g' | figlet`, which gives me something along the lines of:

```
 _   _____       _   _____
/ | |___  |  _  / | |___  |
| |    / /  (_) | |    / /
| |   / /    _  | |   / /
|_|  /_/    (_) |_|  /_/
```

I couldn't get cmdRunner to execute that for me so I created a script.

```
#!/bin/zsh

date '+%H:%M' | sed -e 's/\(.\)/\1 /g' | figlet
```

This lives at `~/dev/wtfrepo/time.sh` and works perfectly well when called from the terminal (I am on macOS). Now I am trying to execute this using cmdRunner.

```yml
    cmdrunner:
      cmd: '~/dev/wtfrepo/time.sh'
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 10
      title: '🕗  Clock'
```

For some reason however my tile only show: `fork/exec ~/dev/wtfrepo/time.s`.
(The end seems to get cut off.)

Would appreciate some help in getting this to run.
Also open for suggestions on better ways to get a bigger clock in there 🙂

**Comment by jonhadfield** [comment]
I tried your example and it showed the same error, but where yours cut off, mine showed:
`fork/exec ~/dev/wtfrepo/time.sh: no such file or directory`
The issue is that it doesn't like the ~. Try using the full path. Worked for me.

**Comment by sam-github** [comment]
I didn't try, but perhaps avoid the script by doing some variation of `cmd: sh -c "date '+%H:%M' | sed -e 's/\(.\)/\1 /g' | figlet"`. The command runner isn't using a shell, so its not getting `~`expanded for the same reason your original shot at using `|` wasn't working, those are shell special characters. You can pass any arbitrary command to sh as a single string, and then it'll interpret the specials. Could avoid the need for the separate script.

**Comment by Seanstoppable** [comment]
Yeah, for things like this, I make sure that the command is on my path (I have ~/bin/ in my path and put shell scripts there). And then I can shorten things by just referencing the script by name, and not by path.

**Comment by HoverBaum** [comment]
Thanks for the help, my config is now working and looks like this:

```
    cmdrunner:
      args: ['-c', '~/dev/wtfrepo/time.sh']
      cmd: 'sh'
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 10
      title: '🕗 Clock'
```

This may look a bit weird but I am also aiming to use my config and associated scripts on multiple machines. Thus portability of also scripts is a concern of mine and I always have a `~/dev/wtfrepo` folder, so I wanna use that instead of an absolute path.

But, using an absolute path also worked 👍
