### ISSUE TITLE
Clocks module "no timezone data available"

### ISSUE THREAD

**Issue by trimble** [wtfutil/wtf#994]
I'm struggling with _sample_configs/sample_config.yml...the clocks modules only show me "no timezone data available". I've also tried replacing one of the modules in the config with the YAML from the clocks module documentation ( https://wtfutil.com/modules/clocks/ )...same result. (Windows host, "running via docker" flavor, mapping _sample_configs/sample_config.yml into container's default config location with -v "$(pwd)/_sample_configs/sample_config.yml:/config/.config/wtf/config.yml").

My sample_config.yml is straight from the master branch. My clocks look like this:
```
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    europe_time:
      title: "Europe"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        GMT: "Etc/GMT"
        Amsterdam: "Europe/Amsterdam"
        Berlin: "Europe/Berlin"
        Barcelona: "Europe/Madrid"
        Copenhagen: "Europe/Copenhagen"
        London: "Europe/London"
        Rome: "Europe/Rome"
        Stockholm: "Europe/Stockholm"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    americas_time:
      title: "Americas"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        UTC: "Etc/UTC"
        Vancouver: "America/Vancouver"
        New_York: "America/New_York"
        Sao_Paulo: "America/Sao_Paulo"
        Denver: "America/Denver"
        Iqaluit: "America/Iqaluit"
        Bahamas: "America/Nassau"
        Chicago: "America/Chicago"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
```
```bash
trimble@logan MINGW64 ~/workspace/wtf (master)
$ MSYS_NO_PATHCONV=1 docker run -it -v "$(pwd)/_sample_configs/sample_config.yml:/config/.config/wtf/config.yml" wtfutil
```
![image](https://user-images.githubusercontent.com/371317/95469415-9f057980-094d-11eb-8280-c0ae74c3e563.png)

Spitballing: something weird with line endings/encoding/formatting?
